[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "sphinx_kroki"
author = "Martin Hasoň"
author-email = "martin.hason@gmail.com"
home-page = "https://github.com/hason/sphinx-kroki"
classifiers = ["License :: OSI Approved :: MIT License"]

[tool.pytest.ini_options]
markers = [
    "sphinx: run test in sphinx project",
]
